spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost/notificationDB
    password: postgres
  flyway:
    create-schemas: true
    schemas: notificationDB
    
server:
  port: 8085
