spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost/productDB
    password: postgres
  flyway:
    create-schemas: true
    schemas: productDB
    
server:
  port: 8083
