spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost/orderDB
    password: postgres
  flyway:
    create-schemas: true
    schemas: orderDB
    
server:
  port: 8084
